### ISSUE TITLE
Can't load my own build to RB960

### ISSUE THREAD

**Issue by mathiasrabe** [adron-s/openwrt-rb2011#2]
Hey,

I tried to build your sourcecode by myself but my RB960 does not boot with my bin files. I tried your precompiled initramfs and I was successful. So I'm wondering what I made wrong. I git cloned you repo and made the step described here: https://openwrt.org/docs/guide-developer/toolchain/use-buildsystem

At the step "make menuconfig" I changed the Target Profile to RB960. I did not change anything else. Also my bin files are larger than yours. What changes have to be done to get your code working?

**Comment by adron-s** [comment]
Hello. Your resulting image is too big. It doesn't fit into memory. RouterBOOT has a size limit for RAM images. Just throw out everything unnecessary from the config and rebuild.

**Comment by mathiasrabe** [comment]
Thanks for the help, now it's booting!
